### ISSUE TITLE
sv_pure_bypass

### ISSUE THREAD

**Issue by Tipsymario3** [kkthxbye-code/csgo_bugs#16]
I can't seem to get the sv pure bypass (first one) to work, it says its not fixed yet but I still get the error. Is it patched or am I just doing something wrong?

**Comment by Tipsymario3** [comment]
nvm, got it to work, it was broken from before

**Comment by AnAkkk** [comment]
The last CS:GO update should have fixed this.

**Comment by szmarczak** [comment]
Yep, it's officially fixed. https://blog.counter-strike.net/index.php/2020/07/31063/

> [MISC]
> – Optimized platform shader files and sound configuration files to be packed inside compressed VPK files.

**Comment by DPTJKKVH** [comment]
@szmarczak Sorry but that's just wrong. A true fix would be to generate the hashes on every map load (and even that leaves room for manipulation).

We can't rule out the possibility that packed files can be swapped after client start so packing the files is very likely just an inconvenience.

**Comment by szmarczak** [comment]
> We can't rule out the possibility that packed files can be swapped after client start

And you're wrong. I've checked that and it didn't work. `VPK`s are loaded only once, when the client starts.

**Comment by szmarczak** [comment]
You can also check the source code btw :P

**Comment by DPTJKKVH** [comment]
Okay, now you stumped me good. Sorry that I was kinda snappy in my first reply.

I was sure that some packed files are loaded twice. Did they change this at some point or am I imaging things?

**Comment by szmarczak** [comment]
> Okay, now you stumped me good. Sorry that I was kinda snappy in my first reply.

No worries, you weren't snappy at all :)

> I was sure that some packed files are loaded twice. Did they change this at some point or am I imaging things?

I looked at the source code from 2015 and found that all VPKs were loaded only once. But the source code is quite old so many things could have been changed since then.

Regarding more recent CS:GO updates, [~2 months ago] I ran Process Monitor and didn't see any VPK file that would be loaded twice (from the time CS:GO opens until a map is loaded).

I don't say that I didn't missed anything, as I may have, so if you're having doubts then feel free to try out Process Monitor for yourself. Two head always better than one :)

**Comment by Tipsymario3** [comment]
Welp, sad if it's patched now, maybe a new exploit will be found some way?

**Comment by szmarczak** [comment]
maybe, no one knows.

**Comment by DPTJKKVH** [comment]
@Tipsymario3 This repo's goal is to get those exploits patched faster by making them public because Volvo is lazy.

Afaik all exploits have been disclosed to Volvo first and only made public when they didn't give a shit.

Go be productive by either doing the same or at least researching your own exploits to use if you are a cheater. 🙃

**Comment by Tipsymario3** [comment]
Tbh tho idk if valve even look at things like this, plus it's not really cheating just because their sound system is literal shit

**Comment by DPTJKKVH** [comment]
It is actually shit I can't argue with that. 😅

**Comment by szmarczak** [comment]
https://github.com/kkthxbye-code/csgo_bugs/pull/17
