### ISSUE TITLE
CLOSE

### ISSUE THREAD

**Issue by Billar42** [kkthxbye-code/csgo_bugs#51]
sv_pure bypass was fixed update 08.01.2020

**Comment by Billar42** [comment]
the models simply cannot be seen through the walls sv pure bypass 9 still works

**Comment by szmarczak** [comment]
it was not

**Comment by FawkesOficial** [comment]
Hello, I've just tested on my own pc and it actually still works.
**Just to be clear:**
What I tested wasn't sv_pure_bypass 8. It was actually using [this video's](https://www.youtube.com/watch?v=AMVHp8a-vz0) models and scripts by @Billar42.

Now, as to the actual sv_pure_bypass 8, I've just tried it and I wasn't able to join an actual server because the game crashed while joining. I suspect that it crashed because the script tried to modify the vpks too early while still joing the server. Maybe its just me.

**Comment by Billar42** [comment]
I was talking about in general about generatewalhack I created new vpk when updating and they did not look carefully at this

**Comment by Billar42** [comment]
@FawkesOficial 
in this video, old vpk, when updating and adding operations, new ones appeared that are not visible through the walls, so you need to constantly update them

**Comment by Billar42** [comment]
make your own vpk files and replace them using sv_pure_bypass_7_2 the result will be no one with old vpk it is, but soon because of this it will crash cs go

**Comment by jama9999** [comment]
how to solve?
[Error: EPERM: operation not permitted, rename 'C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo' -> 'C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo_bak'] {
